### ISSUE TITLE
Escape '+' char on filter query parameter when it is part of the term name

### ISSUE THREAD

**Issue by serguitus** [doofinder/js-doofinder#20]
So when a term looks like ```mouse+keyboard``` the search query should be like ```...&filter[...]=mouse%2Bkeyboard&...```

**Comment by JoeZ99** [comment]
let know
https://support.zoho.com/support/doofinder/ShowHomePage.do#Cases/dv/81d0556c20e6834b115e87f0b3d012070aba6ad3d0c04e99/119940000000007547/0/1459209314971
when done

On Mon, Mar 28, 2016 at 12:54 PM, Sergio Daniel <notifications@github.com>
wrote:

> So when a term looks like mouse+keyboard the search query should be like
> ...&filter[...]=mouse%2Bkeyboard&...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doofinder/js-doofinder/issues/20>
>



-- 
uh, oh <http://www.youtube.com/watch?v=GMD_T7ICL0o>.

<http://www.defectivebydesign.org/no-drm-in-html5>
