### ISSUE TITLE
looks like the addParam method of the controller is useless

### ISSUE THREAD

**Issue by JoeZ99** [doofinder/js-doofinder#21]
according to the doc
https://github.com/doofinder/js-doofinder/#addparam
"Adds new search parameter to the current status."

by looking at the code, `addParam` adds keys to the internal `@status.params` dictionary

But every time `controller.search()`  is called, `@status.params` dict is reseted 
https://github.com/doofinder/js-doofinder/blob/master/src/controller.coffee#L104

so any prior modification made to `@status.params` is overriden.

looks like the method is superfluous, unless it's intended for other thing

@ecoslado, please wight in.

**Comment by ecoslado** [comment]
When you add a filter or a param you won't call `controller.search()` but `controller.refresh()`, so you will use the param you have set.

**Comment by JoeZ99** [comment]
ah,, ok.

On Thu, Mar 31, 2016 at 3:18 AM, Enrique Coslado Santibáñez <
notifications@github.com> wrote:

> When you add a filter or a param you won't call controller.search() but
> controller.refresh(), so you will use the param you have set.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/doofinder/js-doofinder/issues/21#issuecomment-203792919>
>



-- 
uh, oh <http://www.youtube.com/watch?v=GMD_T7ICL0o>.

<http://www.defectivebydesign.org/no-drm-in-html5>
