### ISSUE TITLE
Sending list parameters without number

### ISSUE THREAD

**Issue by sonic182** [doofinder/js-doofinder#229]
a list parameter, example `filter[categories][0]=foo&filter[categories][1]=bar` could be sent as `filter[categories][]=foo&filter[categories][]=bar` which is the standard way

the internal client send's loopable fields (arrays) with the number

This could be changed to, not to use the number?

**Comment by carlosescri** [comment]
Reopening.

Finally, there's no reasonable way to provide an algorithm to encode / decode nested parameters. `qss` library doesn't work very well and we're complicating our life.

I'm going to try to use `qs` again, although it's not an ES6 module and must be embedded in the package to prevent reinventing the wheel.

Decoding is required to provide serialization in our web components repo so I think this is the best solution.

Comments are welcome.

**Comment by carlosescri** [comment]
Also, node's querystring module doesn't support decoding nested parameters.
