### ISSUE TITLE
'df:next_page' is triggered after checking for conditions, but 'df:get_page' not.

### ISSUE THREAD

**Issue by JoeZ99** [doofinder/js-doofinder#25]
for triggering "df:next_page" :

```javascript
  nextPage: (replace = false) ->
    if @status.firstQueryTriggered and @status.currentPage > 0 and not @status.lastPageReached
      @trigger "df:next_page"   
      @status.currentPage++
      @__search(true)
```

that is, **after** it checks that in can actually do the search, it triggers the event

for "df:get_page" :

```javascript
  getPage: (page) ->
    @trigger "df:get_page"
    if @status.firstQueryTriggered and @status.currentPage > 0
      @status.currentPage = page
      self = this
      @__search()
```

*before* doing the pertinent checks, the event is triggered.

which way do you prefer? Personally, I prefer to trigger the event *after* the checkings, but whichever is it, it should be the same for both.

**Comment by ecoslado** [comment]
Right. I agree. We'll put both if the page is actually requested, so if the conditions are ok.
