### ISSUE TITLE
adapt library to new authorization header in v5

### ISSUE THREAD

**Issue by JoeZ99** [doofinder/js-doofinder#27]
check peillis/helpapp#3875

**Comment by JoeZ99** [comment]
@ecoslado

When doing this, I realize if we're going to "enforce" https for search request authenticated via header, then we should make js-doofinder make secure requests. 

I don't know where to find documentation for the `http` library that we require in `client.coffee`, when inspecting the original folder in node_modules , it only shows a single `package.json` file. When going to nodejs documentation, I find that what they say for their `http` module (which is not the same) is that if you want a secure https server, you have to import another (`https`) module.

I'm reluctant to fatter js-doofinder more by adding an extra module, I'm almost convinced that the regular `http` module that we already require can do the job, but can't find doc on it. 

Do you happen to know where I can find some doc about this??

**Comment by JoeZ99** [comment]
looks like it can be done with `http` package.
https://github.com/substack/https-browserify/blob/master/index.js

the `https` package is just a thin wrapper.

**Comment by carlosescri** [comment]
@JoeZ99 what about this?
