### ISSUE TITLE
CloseOnClick is mixing up the history

### ISSUE THREAD

**Issue by abellosovic** [doofinder/js-doofinder#90]
[https://doofinder.freshdesk.com/helpdesk/tickets/6706](https://doofinder.freshdesk.com/helpdesk/tickets/6706)

Hi,

if I use „closeOnClick“: true doofinder is mixing up the browser history:

1. User navigates to site
2. user is browsing (is important)
3. opens product (wich has reviews)
4. User clicks on „Bewertungen“ => below the stars upper right corner (internal named-link with #)
5. Site refreshes(!) not navigates <= bug
6. If user then clicks back (in the browser)
7. User is on main page!!!!!

It is not live in my system but you can simply reproduce.

www.marienfiguren.de

**Comment by carlosescri** [comment]
Moving it to `js-layers`.
